### ISSUE TITLE
Notices "Save Failed." , When I use obsidian-livesync-webclip clip content into own self-host server. But the server works well in Obsidian

### ISSUE THREAD

**Issue by CharisLee** [vrtmrz/obsidian-livesync-webclip#7]
**Server:** 
fly.io APP

**Description:**
Notices "Save Failed." , When I use obsidian-livesync-webclip clip content into own self-host server. But the server works well in Obsidian. And I can clip content into Tasting Server ( https://olstaste.vrtmrz.net/ ). So, Is my server deployment get some wrong ?

**Procedure:**
https://github.com/vrtmrz/obsidian-livesync/discussions/85

**Comment by CharisLee** [comment]
It's solved, In CouchDB'Configuration, enable CORS !

**Comment by chymian** [comment]
@CharisLee  can you pls. post your couchdb config.
is cdb behind a proxy? setup?
